apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
spec:
  destination:
    name: ''
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: loki
    repoURL: 'https://github.com/mlhauber/k8s-fault-detection-cluster.git'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh
spec:
  destination:
    name: ''
    namespace: servicemesh
    server: 'https://kubernetes.default.svc'
  source:
    path: linkerd
    repoURL: 'https://github.com/mlhauber/k8s-fault-detection-cluster.git'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: kube-prometheus-stack
    repoURL: 'https://github.com/mlhauber/k8s-fault-detection-cluster.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
